version: '3'
services:
  mlEngineService:
    container_name: mlengineservice
    image: mlengine-service:local
    build: .
    ports:
      - "9000:9000"
    environment:
      PORT: 9000
    expose:
      - "9000"
