version: '3'
services:
  universityservice:
    container_name: universityservice
    image: university-service:local
    build: .
    ports:
      - "15000:15000"
    environment:
      PORT: 15000
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:32768/postgres