version: '3'
services:
  universityservice:
    container_name: universityservice
    image: university-service:local
    build: .
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:32768/postgres