version: '3'
services:
  universityservice:
    container_name: universityservice
    image: university-service:local
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - ELASTICSEARCH_NODES=http://elasticsearch:9200
